import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('imBAADAAAEAvKAplAplAioAjUAieArdAivDOEBFTAAAAAhODxFzBADABJAABFFAAAAAAHAhhg8AAAVkUAAFDTBGBhPiEgkaKhQhNViVJhPPTFhViQDADBbAgiAAADCAAGBGgrACXANwhEAMBLAUBGAlPBDJhfcMZbbCAJgmOLDguAh2DhiBe4MvkAHBMB');
